name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - name: Set labeled name list as env
      #   id: labeled
      #   run: |
      #     names="${{ toJson(github.event.pull_request.labels.*.name) }}"
      #     echo "names=$names" >> $GITHUB_OUTPUT

      - name: Echo labeled_names local env
        run: |
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"