name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: print all labeled list with json
        run: |
          echo "Labeled list: ${{ toJson(github.event.pull_request.labels) }}"
          echo "Labeled list only name: ${{ toJson(github.event.pull_request.labels.*.name) }}"
