name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: quack-parse-version-actions
        id: version
        uses: duckie-team/quack-parse-version-actions@1.0.1
        with:
          path: playground.txt

      - name: Echo QuackQuack version
        run: echo ${{ steps.version.outputs.version }}
