name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Touch test.txt
        run: touch test.txt

      - name: Create test.txt
        run: echo "test!" > ./test.txt

      - name: Commit and Push generate files
        run: |
          git config user.name "jisungbin"
          git config user.email "ji@sungb.in"
          git add .
          git commit -m "[CI] test"
          git push