name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: print all labeled list with json
        run: echo ${{ fromJSON(github.event.pull_request.labels) }}

      - name: print all labeled list without json
        run: echo ${{ github.event.pull_request.labels }}
