name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: quack-parse-version-actions
        id: version
        uses: duckie-team/quack-parse-version-actions@1.0.0
        with:
          path: "${{ GITHUB_WORKSPACE }}/playground.txt"

      - name: Echo QuackQuack version
        run: |
          echo ${{ steps.version.outputs.version }}
