name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: quack-label-filter-actions
        uses: duckie-team/quack-label-filter-actions@0.0.1
        with:
          labels: "${{ toJson(github.event.pull_request.labels.*.name) }}"
