name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: quack-label-filter-actions
        id: label
        uses: duckie-team/quack-label-filter-actions@1.0.0
        with:
          labels: "${{ toJson(github.event.pull_request.labels.*.name) }}"

      - name: Echo label options!!
        run: |
          echo ${{ steps.label.outputs.bump_type }}
          echo ${{ steps.label.outputs.release_target }}
          echo ${{ steps.label.outputs.publish_module_id }}
          echo ${{ steps.label.outputs.is_snapshot }}
          echo ${{ steps.label.outputs.publish_module_id }}:publish