name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: >
          echo Hello
          World
          This
          Is
          AWESOME!!
          New
          Lines.