name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set labeled name list as env
        id: labeled_name
        run: |
          echo "::set-output name=labeled_names::toJson(github.event.pull_request.labels.*.name)"

      - name: Echo labeled name list without json mapping
        run: |
          echo "${{ github.event.pull_request.labels.*.name }}"

      - name: Echo labeled_names local env
        run: |
          echo "${{ steps.labeled_name.outputs.labeled_names }}"