name: test
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: ${{ 
      contains(github.event.pull_request.labels.*.name, 'test_woo!')
      || contains(github.event.pull_request.labels.*.name, 'test_boo!')
      }}
    runs-on: ubuntu-latest

    steps:
      - name: boo!
        run: echo "boo!"