name: test
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Touch foo.txt
        run: touch foo.txt

      - name: Create foo.txt
        run: echo "foo!" > ./foo.txt

      - name: Touch bar.txt
        run: touch bar.txt

      - name: Create bar.txt
        run: echo "bar!" > ./bar.txt

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: jisungbin
          author_email: ji@sungb.in
          message: '[CI] bump versions'